### PR TITLE
Main documentation rewriting

### PR DESCRIPTION
**Pull request by Betristor**
## Purpose
This PR is for documentation rewriting of DOLPHYN to form a unified structure to incorporate GenX and HSC as well as later CSC documentation together (mainly existing latex description for expressions, code workflow resorting is coming soon). Work on this is being carried on, commits are welcome!
#### Core
- [x] discharge.jl - discharged power from different resources (thermal, VRE, storage) is defined, as well as according variable cost terms.
- [x] investment_discharge.jl - fixed OM costs and investment costs of different resources (thermal, VRE, storage) are defined. capacity constraints on minimum and maximum as well as new construction and retirement constriaints.
- [x] emission_power.jl - carbon emission calculation in power sector.
- [x] non_served_power.jl - variable of non served energy and upper bound constraint is defined.
- [ ] reserves.jl - not touched. The reserve may not be used.
- [x] transmission.jl - line loss and line flow.
- [x] ucommit.jl - variables of online, startup and shutdown states for thermal generators with unit commitment constraints.
#### Policies
- [ ] cap_reserve_margin.jl - quite not understanding the capacity reserve margin constraint.
- [x] co2_cap_power.jl - carbon emission policies for power sector only.
- [x] energy_share_requirement,jl - energy share requirement policy.
- [x] minimum_capacity_requirement.jl - minimum capacity of generation resources policy.
#### Resources
- [x] curtailable_variable_renewable.jl - availability factor and curtailment variable is defined.
- [ ] flexible_demand.jl - partially modified. The resource may not be used.
- [ ] hydro - not touched. The resource may not be used.
- [ ] must run - not touched. The resource may not be used.
- [x] storage: investment_charge.jl - charged power from storage resources is defined, as well as according fixed cost terms and capacity constraints.
- [x] storage: investment_energy.jl - storage energy capacity from storage resources is defined, as well as according fixed cost terms and capacity constraints.
- [x] storage: long_duration_storage - start inventory level of each period. change of inventory level of each representative period. extra bounds on energy capacity.
- [x] storage: storage_all.jl - storage discharge and inventory level decision variables are defined, as well as according variable cost terms and power balance from storage systems. The storage inventory level track constraints and bounds on storage power and energy capacity are also placed here.
- [x] storage: storage.jl - generic description of storage modeling concept.
- [x] storage: storage_asymmetric.jl - partially modified, reserve is not understood. Bounds on charge and discharge power is set.
- [x] storage: storage_symmetric.jl - partially modified, reserve is not understood. Bounds on charge and discharge power is set.
- [x] thermal: thermal_commit.jl - partially modified, reserve is not understood.  Ramping and minimum/maimum output constraints are set. Unit commitment constraints are set.
- [x] thermal: thermal_no_commit.jl - partially modified, reserve is not touched. Ramping and minimum/maimum output constraints are set. 
- [x] thermal: thermal.jl - generic description of thermal modeling frame.
#### Core
- [x] emission_hsc.jl - carbon emission calculation in hydrogen sector.
- [x] h2_investment.jl - fixed OM costs and investment costs of different resources (SMR, storage, electrolysis) are defined.
- [x] h2_non_served.jl - variable of non served hydrogen and upper bound constraint is defined.
- [x] h2_outputs.jl - generated or discharged hydrogen from generation units or storage devices, as well as variable cost terms for hydrogen generation.
#### Policies
- [x] co2_cap_hsc.jl - carbon emission calculation in hydrogen sector.
#### Resources
- [ ] h2_flexible_demand.jl - not touched (mabe it should be deleted).
- [x] g2p: h2_g2p_all.jl - capacity constraints on minimum and maximum as well as new construction and retirement constriaints.
- [x] g2p: h2_g2p_commit.jl - Ramping and minimum/maimum output constraints are set. Unit commitment constraints are set.
- [x] g2p: h2_g2p_no_commit.jl - Ramping and minimum/maimum output constraints are set.
- [x] g2p: h2_g2p_discharge.jl - generated power from hydrogen to power units, as well as variable cost terms.
- [x] g2p: h2_g2p_investment.jl - fixed OM costs and investment costs of hydrogen to power plants.
- [x] g2p: h2_g2p.jl - generic description of hydrogen to powe modeling frame.
- [x] generation: h2_production_all.jl - capacity constraints on minimum and maximum as well as new construction and retirement constriaints.
- [x] generation: h2_production.jl - generic description of hydrogen generation modeling frame.
- [x] generation: h2_production_commit.jl - Ramping and minimum/maimum output constraints are set. Unit commitment constraints are set.
- [x] generation: h2_production_no_commit.jl - Ramping and minimum/maimum output constraints are set. 
- [x] storage: h2_investment_charge.jl - charged hydrogen from storage resources is defined, as well as according fixed cost terms and capacity constraints.
- [x] storage: h2_investment_energy.jl - hydrogen storage energy capacity from storage resources is defined, as well as according fixed cost terms and capacity constraints.
- [x] storage: h2_long_duration_storage - start inventory level of each period. change of inventory level of each representative period. extra bounds on hydrogen storage capacity.
- [x] storage: h2_storage_all.jl - hydrogen storage discharge and inventory level decision variables are defined, as well as according variable cost terms and hydrogen balance from storage systems. The storage inventory level track constraints and bounds on storage power and energy capacity are also placed here.
- [x] storage: h2_storage.jl - generic description of hydrogen storage modeling concept.
- [x] storage: h2_storage_asymmetric.jl - Bounds on charge and discharge power is set.
- [x] storage: h2_storage_symmetric.jl - Bounds on charge and discharge power is set.
- [x] h2_pipeline.jl - hydrogen pipeline storage inventory change. Hydrogen flow between different zones.
- [x] truck: h2_truck.jl - generic description of hydrogen truck modeling concept.
- [x] truck: h2_truck_all.jl - hydrogen truck charge and discharge, states.
- [x] truck: h2_truck_investment.jl - hydrogen truck investment.
- [ ] truck: h2_long_duration_truck.jl - not touched. The function in this file doesn't define useful constraints.
### MarkDown files
- [x] model_notation.md for genx - Primary version submitted, unchecked.
- [x] model_notation.md for hsc - hydrogen supply chain notation rewriting
- [x] data_documentation.md - data documentation of input files is done, output files are left
- [x] model_introduction.md - add hydrogen supply chain introduction into markdown file, truck mdoule waiting for further work
- [x] objective_function.md - total objective is divided into cost terms from sub sectors, genx done, hsc done, csc to be continued
- [x] hydrogen_balance.md  - from generation to pipeline to storage to demand, truck flow waiting for implementation

### CODE REVIEW

**Comment by Betristor** [comment]
@RuaridhMacd I think the documentatio is ready for public, and this branch could be merged now. Sorry for late response.

**Comment by RuaridhMacd** [comment]
@Betristor No problem at all. Thanks for letting me know

**Review by RuaridhMacd — APPROVED** [review]
Still some pieces to look at, but better to incorporate this work now and continue updating piecemeal

**Comment by Betristor** [comment]
I reckon that there is just some pieceworks, the whole structure is setup.

**Pull request merged**
